/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>

using namespace cv;
/* Header for class com_example_nam_healthforyou_MainActivity */

#ifndef _Included_com_example_nam_healthforyou_MainActivity
#define _Included_com_example_nam_healthforyou_MainActivity

JNIEXPORT void JNICALL
Java_com_example_nam_healthforyou_MainActivity_ConvertRGBtoGray(JNIEnv *env, jobject instance,
                                                                jlong matAddrInput,
                                                                jlong matAddrResult) {

    // TODO
}

#ifdef __cplusplus

extern "C" {
#endif
/*
 * Class:     com_example_nam_healthforyou_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_nam_healthforyou_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
