/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_nam_healthforyou_MainActivity_NetworkTask */

#ifndef _Included_com_example_nam_healthforyou_MainActivity_NetworkTask
#define _Included_com_example_nam_healthforyou_MainActivity_NetworkTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
